name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Backup
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
        script: |
          cp /home/javier/mapwithme/.data/database.sqlite /home/javier/backups/`date +"%m%d%Y_%H_%M_%S".sqlite`

    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}
      with:
         source: "."
         target: "/home/javier/mapwithme"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          nvm use 15.8.0
          yarn --cwd /home/javier/mapwithme
          pm2 restart map
